[tool.pylint]
ignore = [".venv", "old"]
ignore-patterns = ["__pycache__", ".pytest_cache"]
disable = [
    "logging-fstring-interpolation",    # W1203
    "f-string-without-interpolation",   # W1309
    "broad-exception-caught",           # W0718
    "missing-module-docstring",         # C0114
    "missing-class-docstring",          # C0115
    "missing-function-docstring",       # C0116
    "line-too-long",                    # C0301
    "too-few-public-methods",           # R0903
    "too-many-instance-attributes",     # R0902
    "too-many-arguments",               # R0913
    "too-many-positional-arguments",    # R0917
]

[tool.pytest.ini_options]
# log_cli = true  # Uncomment this if you need it
addopts = "-q --tb=short -s"
log_cli_level = "INFO"
log_cli_format = "%(asctime)s - %(levelname)s - %(name)s - %(message)s"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
testpaths = [
    "tests"
]

