# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]

# Assume Python 3.10
target-version = "py310"

[lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`) codes by default.
# Unlike Flake8, Ruff doesn't enable pycodestyle warnings (`W`) or
# McCabe complexity (`C901`) by default.
select = ["ALL"]
ignore = ["D203", "D212", "E501"]

[lint.per-file-ignores]
# "src/jobs/remove_bad_files.py" = ["ERA001"]
"tests/settings/test__user_config_from_env.py" = ["S101"]
"tests/jobs/test_strikes_handler.py" = ["S101", "SLF001"]
"tests/jobs/test_remove_unmonitored.py" = ["S101", "SLF001"]
"tests/jobs/test_remove_stalled.py" = ["S101", "SLF001"]
"tests/jobs/test_remove_slow.py" = ["S101", "SLF001"]
"tests/jobs/test_remove_orphans.py" = ["S101", "SLF001"]
"tests/jobs/test_remove_missing_files.py" = ["S101", "SLF001"]
"tests/jobs/test_remove_metadata_missing.py" = ["S101", "SLF001"]
"tests/jobs/test_remove_failed_imports.py" = ["S101", "SLF001"]
"tests/jobs/test_remove_failed_downloads.py" = ["S101", "SLF001"]
"tests/jobs/test_remove_bad_files.py" = ["S101", "SLF001"]
"tests/jobs/test_removal_handler.py" = ["S101", "SLF001"]
